### ISSUE TITLE
Support for accelerator modelling?

### ISSUE THREAD

**Issue by NazerkeT** [MEEPproject/coyote#1]
Hi there!

Thanks for this tool-chain!

I recently found this work and have following questions:

1) Is it possible to model accelerators at a high level with a coyote instead of the processors or vector lanes? If no, how hard will it be to add this feature to the system?

2) If I can model accelerators, can I also model instructions running at each accelerator, then to get performance numbers?

3) If I wanna add new instructions via spike, can I still run the program?

Thanks,
Best wishes,

**Comment by perezpavonb** [comment]
Hello,

First of all, apologies for a very late reply. In answer to your questions:

1. It depends on what you mean by an accelerator. Coyote has been used in fact to study a self-hosted RISC-V accelerator. However, if you mean an accelerator in the traditional sense (host-device programming model), then that would be challenging. If you can do with just some custom instructions representing the accelerator, then that should not be hard.
2. Yes, you can add your own instructions and get performance numbers regarding the memory hierarchy. You should add these to spike.
3. Yes, you can. You need to follow the same steps that you would for plain spike.

Best,
Borja

**Comment by NazerkeT** [comment]
Hi @perezpavonb!

Thanks for your response, they clarify important points for me!

Will let you know if I will have any issue using it later the month :)

Best wishes,
